EvolutionAPI/evolution-api

src/whatsapp/dto/sendMessage.dto.ts, src/whatsapp/services/whatsapp.service.ts
Dessa forma, permite desativar o link preview, caso não precisa, basta informar no options, `linkPreview: false`
=> Add LinkPreview Option

src/validate/validate.schema.ts, src/whatsapp/controllers/chat.controller.ts, src/whatsapp/dto/chat.dto.ts, src/whatsapp/routers/chat.router.ts, src/whatsapp/services/whatsapp.service.ts
Reverts EvolutionAPI/evolution-api#18
=> Revert "Adição de FetchProfile"

src/whatsapp/services/whatsapp.service.ts
Os grupos antigamente tinha `-` e mais de 24 caracteres, os grupos novos não tem mais o `-` e tem mais de 18 caracteres.
=> Validação de Grupo

Docker/mongodb/docker-compose.yaml, Docker/redis/docker-compose.yaml, docker-compose.yaml.example, docker-compose.yaml.example.complete, docker-compose.yaml.example.dockerhub, docker.sh
SH code to check existence of unnecessary docker network.
```yaml
external: true
```
It is only for using an existing main network.
Since the `docker-compose*.yml` files are already primarily responsible for provisioning the main application stack, it doesn't make sense to create the network in a task outside its scope.
This is just a small contribution from someone who has just arrived and is already impressed with this community!
The docker build command will be removed in future releases in favor of [buildx](https://docs.docker.com/build/architecture/#buildx).
The Dockerfile build can be done by `docker-compose*.yml` itself by adding the `build: .` property in the api service.
=> clean: docker network declaration and build of the `evolution/api` image

src/whatsapp/controllers/instance.controller.ts
Essa correção resolve o problema de quando criar uma conexão utilizando o rabbitmq ou websocket falhar ao consumir uma mensagem.
=> Fix set event rabbitmq/websocket

src/config/env.config.ts
```This comparison appears to be unintentional because the types 'string' and 'number' have no overlap.```
=> Correção de Erro

src/whatsapp/services/chatwoot.service.ts
Due to Chatwoot's limitation in not displaying rich metadata (open graph, twitter card, etc.) in conversations on the attendants' dashboard, messages coming from advertisements that contain this metadata arrive without any reference, meaning that attendants do not know which announcement the contact is coming from.
This implementation creates a message containing an attachment from the rich metadata coming from the ad message, as well as the title, description, and source url, in addition to the contact message itself.  Thus trying to emulate the default behavior in the WhatsApp application.
This implementation must be improved and must use the `cards` message creation approach in ChatWoot as soon as it starts to support this type of message in the Dashboard (Inboxes) and provide the …
=> Initial support for preview and reference from Ads messages on Chatwoot

src/whatsapp/dto/typebot.dto.ts, src/whatsapp/models/typebot.model.ts, src/whatsapp/services/typebot.service.ts
Este PR aborda a solicitação de recurso mencionada na issue #124. Adiciona mudanças que aprimoram a função `startTypebot` para criar uma sessão persistente, inicializando o `sessionId` em StartTypebot.
- A função `startTypebot` agora tem a capacidade de:
- Criar uma nova sessão persistente.
- Vincular o `sessionId` desde o início, garantindo uma continuidade nas interações subsequentes.
- Passar variáveis em startTypebot que são consistentes para no typebot.
- Atualizado o DTO e o Modelo do Typebot para acomodar `prefilledVariables`.
- Resolve o problema de reinicialização do bot durante a primeira interação do usuário no WhatsApp.
- Proporciona uma experiência de usuário mais fluída associando o `sessionId` logo de início.
1. Inicie um bot usando o endpoint "Start Typebot" informando …
=> Melhoria no método "startTypebot" para criar sessão persistente quando acionado

src/dev-env.yml, src/whatsapp/controllers/instance.controller.ts, src/whatsapp/dto/instance.dto.ts, src/whatsapp/models/webhook.model.ts, src/whatsapp/services/webhook.service.ts, src/whatsapp/services/whatsapp.service.ts, src/whatsapp/types/wa.types.ts
Foi criado uma nova alteração para recuperar o base64 de arquivos de media enviar por webhook
Foi acrescentado no arquivo de env  a variável **WEBHOOK_BASE64** que por padrão vem desativado. 
Também foi criar a plausibilidade de enviar o evento ao criar o webhook. 
Imagem de retorno
=> Recuperar base64 de media enviada por webhook

src/whatsapp/services/typebot.service.ts
Corrige erro no endpoint {{baseUrl}}/typebot/start/{{instance}}
- Adiciona verificação para garantir que `variables `não esteja vazio antes de executar o foreach.
=> Fix: Variables null

.vscode/settings.json, CHANGELOG.md, src/whatsapp/services/typebot.service.ts
Refactor TypebotService to handle error responses from axios
The TypebotService in `typebot.service.ts` file has been refactored to handle error responses from the axios library. Error handling has been added to the `startTypebot`, `createNewSession`, and other related methods to catch and log errors from failed axios requests.
=> Handle erros in Typebot

src/whatsapp/controllers/instance.controller.ts
When deleting a instance in a connecting state, the event remove.instance was not triggered.
=> Deleting instances

src/whatsapp/services/whatsapp.service.ts
Foi removido o await do disparo do webhook ao enviar uma mensagem!
**Motivo**
Quando uma aplicação chamava a rota de enviar mensagem e o webhook estive apontado para a mesma aplicação
a evolution simplesmente trava até que a função que fez a chamada para o envio de mensagem retornasse um time out e a evolution conseguia fazer o disparado do webhook.
Após remover o await tudo funcionou corretamente
=> fix: Removed await from webhook when sending a message

src/whatsapp/services/chatwoot.service.ts
It was observed that not all messages arrived on Chatwoot, I carried out stress tests on the computer to simulate and correct it.
When our server was overloaded, some messages did not arrive on Chatwoot, when looking at the logs and code, we noticed that when Evolution Api receives a message, the contact's profile photo is updated to Chatwoot, if for some reason it fails this PATCH, the evolution API did not continue with the message, I made a treatment so that if this happens, the "contact" object does not become null.
As a result, messages were no longer lost.
=> fix messages not received: error handling when updating contact

src/whatsapp/services/typebot.service.ts
There's no underline in WhatsApp ~ use strikethrough instead, I switched to * bold.
=> Update typebot.service.ts - element.underline change ~ for *

src/whatsapp/services/typebot.service.ts
The modification is centered around handling cases where a session status update is attempted for a non-existent session. Previously, the service only updated the status of existing sessions. With this update, if a session does not exist when attempting to update its status, a new session is created.
Key Changes:
1. Added an 'else' block in the Typebot Service to handle the scenario where a session is not found.
2. In this block, a new session is initialized with a unique sessionId, the current status, creation and update timestamps, and prefilled variables including `remoteJid`.
3. This new session is then added to the `findData.sessions` array, ensuring that the service can manage sessions that were not previously tracked.
=> Add session creation for typebot service

src/whatsapp/services/typebot.service.ts
Correção para https://github.com/EvolutionAPI/evolution-api/pull/233 onde eu coloquei um `else` para criar a sessão quando não existe uma sessão, o objetivo era para pausar a sessão antes mesmo de existir, porem com os testes @matiasduartee quando é tem uma sessão aberta e usa o end-point para mudar o status para `closed` funciona normalmente, a API apaga a sessão, porem se enviar novamente como `closed` o código criava uma sessão com o status `closed` que fazia o bot parar de funcionar.
Para corrigir, agora ele só cria sessões caso não exista e o status seja `paused`, visto que o open já possui um end-point
=> fix: only create if is paused

Docker/.env.example, src/config/env.config.ts, src/dev-env.yml, src/whatsapp/services/typebot.service.ts
Simplesmente adiciona um novo env `TYPEBOT_KEEP_OPEN` que tem como valor padrão `false`, porem quando está como `true` impede o fechamento da sessão no fim do fluxo do typebot para atender as requisições feita no issue  https://github.com/EvolutionAPI/evolution-api/issues/273
=> simple add keep open

src/validate/validate.schema.ts, src/whatsapp/controllers/chatwoot.controller.ts, src/whatsapp/dto/chatwoot.dto.ts, src/whatsapp/models/chatwoot.model.ts, src/whatsapp/services/chatwoot.service.ts, src/whatsapp/services/whatsapp.service.ts
Nesse PR foram feitas 2 coisas solicitadas pelo @edisoncm-ti
1. Corrigido a formatação do **Negrito**, _Italico_ e Sublinhado usando Regex
2. Adicionado a propriedade `sign_delimiter` na configuração do Chatwoot, permitindo definir um delimitador diferente para a assinatura. Padrão quando não definido `\n`
Extra: Essa nova opção já foi adicionado ao Manager: https://github.com/EvolutionAPI/evolution-manager/pull/7
=> Chatwoot format

src/whatsapp/services/chatwoot.service.ts
Esse PR muda o código para o nome usar o nome de exibição do agente preferencialmente ao invés do nome completo.
Mantendo o nome completo como "fallback" caso o nome de exibição não esteja definido
=> Chatwoot Agent Name

src/config/env.config.ts, src/dev-env.yml, src/main.ts, src/whatsapp/routers/index.router.ts
Adiciona 2 envs que permitem desativar o `/docs` e `/manager`, por padrão o manager e docs estão sempre ativados, para desativar é preciso adicionar no arquivo env
`DISABLE_DOCS=true`
`DISABLE_MANAGER=true`
=> Add options to disable docs and manager

src/whatsapp/services/chatwoot.service.ts
In some cases mimeTypes.extension() return false to csv and other file types
=> fix(chatwoot): when possible use the original file extension

src/whatsapp/services/whatsapp.service.ts
Corrects the generation of the hash variable name, error when generating with white spaces and special characters.
**Error:**
```json
{
"status": 500,
"error": "Internal Server Error",
"response": {
"message": "Command failed: /root/evolution-api/node_modules/@ffmpeg-installer/linux-x64/ffmpeg -i /root/evolution-api/store/temp/temp-+55 (99) 9 9999-9999-1704891424843.mp3 -vn -ab 128k -ar 44100 -f ipod /root/evolution-api/store/temp/+55 (99) 9 9999-9999-1704891424843.mp4 -y\n/bin/sh: 1: Syntax error: \"(\" unexpected\n"
}
}
```
**Fix:**
Added the parameter ```number = number.replace(/\D/g, "");``` before the line ```const hash = ${number}-${new Date().getTime()};``` to remove any non-numeric characters in the ```processAudio``` function.
=> Fix: Corrects the generation of the hash variable name

src/config/env.config.ts, src/dev-env.yml, src/libs/cacheengine.ts, src/libs/localcache.ts, src/libs/rediscache.client.ts, src/libs/rediscache.ts, src/whatsapp/abstract/abstract.cache.ts, src/whatsapp/controllers/chatwoot.controller.ts, src/whatsapp/controllers/instance.controller.ts, src/whatsapp/services/cache.service.ts, src/whatsapp/services/chatwoot.service.ts, src/whatsapp/services/monitor.service.ts, src/whatsapp/services/whatsapp.service.ts, src/whatsapp/whatsapp.module.ts
É possível escolher entre usar cache local, redis ou desabilitar. Também pode configurar um tempo padrão de expiração das chaves. A ideia foi criar um serviço que possa ser usado no futuro em outros locais.
Foram adicionados estes campos no env.yml: 
`CACHE:
REDIS:
ENABLED: false
URI: "redis://localhost:6379"
PREFIX_KEY: "evolution-cache"
TTL: 604800
LOCAL:
ENABLED: false
TTL: 86400`
Eu criei um novo cliente para o redis porque tem alguns tratamentos especificos no atual para trabalhar com a baileys. Fiquei com receio e preferi não alterar o original. Se alguém quiser otimizar seria ótimo.
Também tentei seguir os padrões do projeto mas honestamente talvez não tenha ficado 100%, então se algo estiver fora, por favor corrija ou me avise.
=> feat(cacheservice): add support to use use redis in cacheservice

src/whatsapp/services/whatsapp.service.ts
Fixed when requested to publish status message, it goes into the condition of not being audio and also the jid is defined as "+status@broadcast"
=> fix: Sending status message

src/whatsapp/dto/chat.dto.ts, src/whatsapp/services/whatsapp.service.ts
When requesting if the Whatsapp number is valid, if the number sent contains the 9 digit from Brazil, and the result comes without that digit, there's no way to identify the number sent inside the response array.
With this change the response DTO will become like this:
With that when the API returns the list of valid numbers I can identify that exact number I sent
=> Add number parameter to OnWhatsAppDto constructor

src/whatsapp/services/typebot.service.ts
- Remove quebra de linha no index final do array
Foi realizada alteração para permitir a quebra de linha correta, quando usada em um array dentro de um script, como na imagem abaixo:
Quanto existe um \n no final da última linha do array **(1)**, o Typebot acabou criando um novo nó só com a quebra, mas sem a informação do nó children **(2)**. Isso alterou a estrutura que foi criada na Evo, que interpretou como não iterável, já que está fora do array.
- Obtem a resposta de um sendList (Lista)
Este é um recurso bastante pedido pelos usuários do Typebot e foi solicitado na Issue https://github.com/EvolutionAPI/evolution-api/issues/329, onde consta uma descrição mais detalhada da forma de uso.
=> Typebot: Remove quebra de linha no index final do array | Obtem a resposta de um sendList (Lista)

package.json, src/validate/validate.schema.ts, src/whatsapp/controllers/group.controller.ts, src/whatsapp/dto/group.dto.ts, src/whatsapp/routers/group.router.ts, src/whatsapp/services/whatsapp.service.ts
Method GET: `{{baseUrl}}/group/acceptInviteCode/{{instance}}?inviteCode={{inviteCode}}`
exemplo de resposta sucesso:
```
{
"accepted": true,
"groupJid": "120363162848345081@g.us"
}
```
=> Join in Group by Invite Code

package.json, src/utils/makeProxyAgent.ts, src/whatsapp/controllers/proxy.controller.ts, src/whatsapp/dto/chat.dto.ts, src/whatsapp/services/whatsapp.service.ts, src/whatsapp/whatsapp.module.ts
Hello, I've conducted some tests using the `new ProxyAgent()` on the `testProxy` function when adding a new proxy (the same agent that is sent to Baileys). However, when using it, the IP did not change.
- I changed it to use the [HttpsProxyAgent](https://www.npmjs.com/package/https-proxy-agent), and when using it, it worked as expected.
- I also changed the website to check the IP address from meuip.com.br to icanhazip.com. When using meuip.com.br, I encountered some errors due to Cloudflare protection. After changing the website, the error was resolved.
- I extracted the proxy agent creation into a function that can be used anywhere, ensuring the use of the same agent for all instances.
- Additionally, I added a validation to check if the instance exists before attempting to add a proxy …
=> Proxy improvements

src/whatsapp/services/chatwoot.service.ts
Existe cenários onde é utilizado no ChatWoot com numeros que não são providos pela EvolutionAPI.
Por exemplo, na Cloud API, os numeros utilizados estão com 9.
Quando envia uma nova mensagem para esses números utilizando a EvolutionAPI, a mensagem é enviada normalmente, mas quando recebe, é criado um novo contato, pois o número está sem o 9.
Com isso, fiz a implementação para buscar novamente o número caso for DDI do Brasil, não pode ser grupo e que tenha mais de 13 caracteres.
+55 XX X XXXXXXXX
Será feito a remoção do 9 e feito uma nova busca no Chatwoot.
=> Fix with nine number brazil

src/whatsapp/services/whatsapp.service.ts
In `chat/whatsappNumbers` and `chat/fetchProfile` routes, name will be filled if stored
=> feat: If contact stored with name, name added in return

src/utils/translations/en.json, src/utils/translations/pt-BR.json, src/whatsapp/services/chatwoot.service.ts, src/whatsapp/services/whatsapp.service.ts
If a message is sent to a number that does not exist on WhatsApp, a private error message will be returned informing the user that the message was not delivered.
PT-BR
Caso seja enviado uma mensagem para um numero que não exite no whatsapp será devolvido uma mensagem privada de erro informando o usuário que aquela mensagem não foi entregue.
=> Feat Chatwoot - Reject Message If is not a valid wpp number

src/whatsapp/services/chatwoot.service.ts
Adicionar o identifier na busca do contato, conforme discussão https://github.com/EvolutionAPI/evolution-api/pull/393 pode acontecer de contatos terem somente o identifier no contato e não o numero de telefone.
Ainda existe um caso a ser tratado:
Caso o contato for o primeiro a chamar e não tiver o 9 e posteriormente um usuário cadastrar o numero com o 9 digito nos contatos vai continuar duplicando da mesma forma. Teríamos que dar um jeito de sempre preferir o contato com telefone com mais dígitos.
=> Fix(chatwoot): Include identifier to contact filter

package.json, src/config/env.config.ts, src/dev-env.yml, src/docs/swagger.yaml, src/libs/postgres.client.ts, src/utils/chatwoot-import-helper.ts, src/validate/validate.schema.ts, src/whatsapp/controllers/chatwoot.controller.ts, src/whatsapp/controllers/instance.controller.ts, src/whatsapp/dto/chatwoot.dto.ts, src/whatsapp/dto/instance.dto.ts, src/whatsapp/dto/settings.dto.ts, src/whatsapp/models/chat.model.ts, src/whatsapp/models/chatwoot.model.ts, src/whatsapp/models/contact.model.ts, src/whatsapp/models/message.model.ts, src/whatsapp/models/settings.model.ts, src/whatsapp/repository/chat.repository.ts, src/whatsapp/repository/contact.repository.ts, src/whatsapp/repository/message.repository.ts, src/whatsapp/services/chatwoot.service.ts, src/whatsapp/services/whatsapp.service.ts, src/whatsapp/types/wa.types.ts
Messages are imported direct to chatwoot database. Media and group messages are ignored.
New env.yml variables: 
CHATWOOT_IMPORT_DATABASE_CONNECTION_URI: URI to connect direct on chatwoot database. CHATWOOT_IMPORT_PLACEHOLDER_MEDIA_MESSAGE: Indicates to use a text placeholder on media messages.
New instance setting: 
sync_full_history: Indicates to request a full history sync to baileys.
New chatwoot options:
import_contacts: Indicates to import contacts.
import_messages: Indicates to import messages.
days_limit_import_messages: Number of days to limit history messages to import.
=> feat(chatwoot): import history messages to chatwoot on whatsapp connection

src/whatsapp/repository/contact.repository.ts, src/whatsapp/routers/chat.router.ts, src/whatsapp/services/whatsapp.service.ts
Currently, for every number checked, a database call is made to verify if the JID is saved and to return the name, but this can be improved to check everything only once.
In the current code, checking 92 numbers took 750ms, as shown here:
With the current improvement, checking the same 92 numbers results in a 321ms request:
The more numbers you send, the slower it becomes.
=> Improvement on whatsapp number validation

src/utils/i18n.ts, src/whatsapp/abstract/abstract.router.ts, src/whatsapp/controllers/settings.controller.ts, src/whatsapp/repository/auth.repository.ts, src/whatsapp/routers/chatwoot.router.ts, src/whatsapp/routers/settings.router.ts, src/whatsapp/services/chatwoot.service.ts, src/whatsapp/services/monitor.service.ts
When we create an instance and don't read the QR code, some documents are created in the database but not in the instance collection. As a result, after restarting the API, the instance disappears but the database still retains some leftover data.
And after we restart the API:
---
With this change, when starting the API, it will check all documents from the 'auth' collection and compare if the instance exists.
Also, some commented sections have been cleaned.
=> Temp instance deletion

src/whatsapp/services/whatsapp.service.ts
With this change, first, we add all contacts to the database to improve the response time when the user fetches the contact list. After saving everything to the database, we then call another event to update the profile pictures for all contacts that have already been saved.
The contact save event occurred from 2:09.341 (m:ss.mmm):
To 18.367ms:
And after that it takes the time required to update all the profile pictures
_This tests has been made with 863 contacts_
=> Extracted profile picture request from contacts.upsert function

src/whatsapp/models/chat.model.ts, src/whatsapp/models/contact.model.ts, src/whatsapp/repository/chat.repository.ts, src/whatsapp/services/whatsapp.service.ts
This is a hotfix for this PR: https://github.com/EvolutionAPI/evolution-api/pull/409
In this change we removed the label save to contact, since the return is chat and not contact and added the label list to chat fetch (if save chat is enabled)
Change on the `/chat/findChats/{instance}` endpoint:
Added labels associated array
Also, the webhook **labels.association** changed the `jid` to `chatId` for better understanding.
=> Changed label update to chat instead of contacts

src/whatsapp/services/whatsapp.service.ts
In some connections, the event `contacts.upsert` is not called, and the contacts are not saved in the database.
With this change, we call the `contacts.upsert` with the contacts received in the message history (`messaging-history.set`). This is only called if the contact received has a name, to avoid replacing preexisting contacts with a name.
To make it work properly, the setting `sync_full_history` must be enabled (check this issue from Baileys: [Baileys Issue #470](https://github.com/WhiskeySockets/Baileys/issues/470)).
Also, with this change, it will save all contacts that you have messaged with, and not only your saved contacts.
Check some issues with this error from the Baileys repo:
[Baileys Issue #522](https://github.com/WhiskeySockets/Baileys/issues/522)
[Baileys Issue …
=> Implement contact upsert in messaging-history.set

src/whatsapp/controllers/proxy.controller.ts
The application logs `proxy enabled` before conducting the proxy tests. In some cases, the request doesn't return any error, but the data is not accessible. An additional handler has been added for that.
=> Improve proxy error handling

src/whatsapp/services/whatsapp.service.ts
Currently, the return of the group participants list exactly mirrors what is returned from WhatsApp. In this pull request, we have added a function to check the database for saved contacts. If the participant's name or profile picture doesn't exist but is present in the database, we will use the saved data instead of returning null or empty.
=> Refactor fetching participants for group in WhatsApp service

Docker/.env.example
- Variáveis do Docker referente ao feat #395  
- Docker variables related to the feat #395
=> Update variables  .env.example docker 

src/validate/validate.schema.ts
Removida a obrigatoriedade da descrição do rows para ser algo opcional.
Isso permite os "circulos" das opções ficarem mais alinhados com os titulos sem a necessidade de adicionar espaço em branco caso não queira adicionar a descrição.
{
"number": "559999999999 (Recipient number with Country Code)", "options": {
"delay": 1200,
"presence": "composing"
},
"listMessage": {
"title": "List Title",
"description": "List description",
"buttonText": "Click Here",
"footerText": "footer list\nhttps://examplelink.com.br", "sections": [
{
"title": "Row tilte 01",
"rows": [
{
"title": "Title row 01",
"description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,", "rowId": "rowId 001"
},
{
"title": …
=> Removido obrigatoriedade de descrição dos rows do sendList

src/whatsapp/services/typebot.service.ts
Currently, change status endpoint return every session on typebot for the instance. This change makes so that only the session requested to be changes is returned.
=> changed returned sessions on typebot status change

src/whatsapp/services/chatwoot.service.ts
Acredito que isso deve ser um bug na própria baileys mas pelo que verifiquei, usando o WhatsApp desktop com mensagens temporárias habilitadas, o padrão de mensagem que recebemos é diferente.
Este ajuste apenas contorna este formato fora do padrão. Um pouco gambiarra mas faz parte rs
=> fix(chatwoot): fix when receiving/sending messages from whatsapp desktop with ephemeral messages enabled

src/whatsapp/services/chatwoot.service.ts
if contact has more than one conversation, we could get the wrong conversation.
=> fix(chatwoot): fix conversation read on chatwoot version 3.7

src/api/integrations/chatwoot/services/chatwoot.service.ts
In chatwoot version 3.8 we can't use the filter operator 'contains' for the field 'identifier'
=> fix(chatwoot): error: invalid operator. The allowed operators for identifier are [equal_to,not_equal_to]

src/api/models/message.model.ts, src/api/services/whatsapp/whatsapp.baileys.service.ts
Ajuste para adicionar o status da mensagem junto ao webhook `MESSAGES_SET`, disparado com o evento `messaging-history.set` da baileys.
Ajuste visando facilitar a identificação do status da mensagem (pendente, entregue, lido, ...)  no momento da importação do histórico.
Estou utilizando esse ajuste no meu fork a algum tempo, tem funcionado sem problemas.
-----
**O que muda?**
Um novo campo `status` é enviado no conteudo do webhook MESSAGES_SET, possiveis valores são:
```javascript
'ERROR' | 'PENDING' | 'SERVER_ACK' | 'DELIVERY_ACK' | 'READ' | 'PLAYED'
```
_(basicamente os valores disponiveis em wa.StatusMessage no formato de string.)_
Obs.: Não consegui testar com Chatwoot e Typebot, utilizo apenas a api "pura"
=> Adicionado message.status ao webhook MESSAGES_SET

package.json, src/api/integrations/chatwoot/services/chatwoot.service.ts
Atualizado Baileys para corrigir o erro de 'init queries' https://github.com/WhiskeySockets/Baileys/issues/764
FIX #574
Refatorado o método getOpenConversationByContact, o chatwoot alterou sua api de filtro de conversas e não aceita mais o parâmetro contact_id, com isso não é mais possível buscar conversas abertas para o contato especifico, portanto, foi alterado para a api de contacts para buscar as conversas do contato e filtrar a conversa aberta.
Esse erro impacta a geração e envio do QR Code para o chatwoot e mensagens do 'Bot' +123456.
=> fix(chatwoot): getOpenConversationByContact and init queries error

package.json, src/api/integrations/sqs/libs/sqs.server.ts
https://aws.amazon.com/pt/blogs/developer/announcing-end-of-support-for-aws-sdk-for-javascript-v2/
=> chore(aws sqs): update aws sdk v3

.github/workflows/publish_docker_image.yml
Sugestão de build automatizado das imagens amd64 e arm64.
Esse exemplo usa o próprio GitHub como register para as imagens.
Esse é o resultado final: https://github.com/stack-app-br/evolution-api/pkgs/container/evolution-api
PS: Precisa atualizar o DOCKER_TAG se vcs resolverem adotar essa abordagem.
Enviar para o docker hub também não é muito diferente.
=> chore: build docker image to platforms: linux/amd64, linux/arm64

src/config/env.config.ts
Este PR tem como objetivo resolver esta issue: 
- https://github.com/EvolutionAPI/evolution-api/issues/589
Nela eu deixei melhor descrito que a variável de ambiente CLEAN_STORE_CLEANING_INTERVAL não está sendo utilizada, mas sim sendo substituída por uma que não existe. Também adicionei exemplos e algumas evidências.
Fico a disposição para qualquer correção necessária!
=> Corrigindo variável inexistente do arquivo env.config.ts e substituindo pela correta CLEAN_STORE_CLEANING_INTERVAL 

Docker/.env.example, src/dev-env.yml
As initially mentioned in Issue https://github.com/EvolutionAPI/evolution-api/issues/480, there was a need to pass an SSL configuration parameter in the Postgres connection string, to enable contact synchronization.
If this parameter is not informed, the following message will be displayed:
`[ChatwootImport] [string] Error on import history contacts: Error: The server does not support SSL connections`
To prevent new users from wasting time, if they are not aware of this need, include the parameter in the files 
- scr/dev-env.yml
- Docker/.env.example
So, just adjust the rest of the string with the Postgres connection data and the synchronization will work automatically.
Hugs and let's go! 🚀
=> fix: Correction to Postgres connection string in environment files

src/api/services/channel.service.ts, src/api/types/wa.types.ts
Foi adicionado o parâmetro 'merge_brazil_contacts' ao channel.service.ts e wa.types.ts também alguns logs foram acionados para manter a consistência e o padrão de logs e tipagem. 
A funcionalidade não foi afetada, portanto, trata-se de um minor fix.
=> fix(chatwoot): add merge_brazil_contacts flag to ChannelStartupService and add logs

src/api/integrations/chatwoot/services/chatwoot.service.ts
Quando uma mensagem com imagens GIF é enviada, ela não é recebida pelo WhatsApp no telefone. A mensagem é recebida no WhatsApp Web e no WhatsApp Desktop, mas não no WhatsApp Mobile.
Tentei enviar o GIF como vídeo, mas não deu certo. Enviar como imagem também parece não ser suportado.
A solução é enviar como documento, que é a mesma abordagem usada pelo WhatsApp Web e Desktop para o tratamento de imagens GIF.
Apenas GIFs enviados diretamente pelo celular são lidos corretamente.
=> fix: added validation when sending gif image

src/api/integrations/chatwoot/services/chatwoot.service.ts
Adicionado sufixo cwId quando está sendo buscada caixa de entrada para manter compatiblidade com caixas antigas.
=> Add -cwId- when findByName

src/api/controllers/instance.controller.ts
A rota /instance/create não estava sempre definindo o groups_ignore mesmo marcado como false pois avia um comparador false || true que sempre retornaria true, então adicionei uma solução que mantem a compatibilidade anterior caso o valor não seja definido o groups_ignore sera true.
=> Fix: groups_ignore in /instance/create and maintaining compatibility

prisma/mysql-schema.prisma, prisma/postgresql-schema.prisma, src/api/services/channels/whatsapp.baileys.service.ts
- Updated BaileysStartupService to include disconnection handling logic.
- Enhanced Instance model to store disconnection status and details.
- Handled specific error codes to manage disconnection states:
- 401: Triggered logout to handle unauthorized access.
- 402: Recognized as temporary ban, reconnection attempts paused.
- 403: Recognized as forbidden, reconnection attempts stopped.
- 406: Recognized as permanent ban, reconnection attempts halted.
=> Improve reconnection logic for ban and block cases and add disconnection information to BaileysStartupService and Instance model

prisma/mysql-schema.prisma, prisma/postgresql-migrations/20240811021156_add_chat_name_column/migration.sql, prisma/postgresql-schema.prisma, src/api/services/channel.service.ts, src/api/services/channels/whatsapp.baileys.service.ts, src/api/services/channels/whatsapp.business.service.ts
With this we'll have the group identification on the chat's table:
Also added a validation if the session exists before deleting it when disconnecting to avoid this:
Currently storing the session on redis not on the database
=> V2 save chat name

prisma/mysql-schema.prisma, prisma/postgresql-migrations/20240811183328_add_unique_index_for_remoted_jid_and_instance_in_contacts/migration.sql, prisma/postgresql-schema.prisma, src/api/services/channels/whatsapp.baileys.service.ts
In this PR we made the contacts unique in the same instance to avoid duplicated records on the database.
Along with that the contact update section has been fixed, it was using `updateMany`, but since we're updating different values the updateMany won't work in this case, it has been implemented the `$transactions` from prisma.
See ref: https://stackoverflow.com/a/71509069
=> V2 update contacts database

src/api/integrations/chatwoot/services/chatwoot.service.ts, src/api/services/channels/whatsapp.business.service.ts
When using an Instance with the Cloud API (Meta) Integration, media files such as images, audio, and documents arrived in Chatwoot as attachments without file extensions, as shown in the image below:
Meta uses the "filename" property for files like documents that have a filename. The change below retrieves the filename with its extension and sends it correctly to Chatwoot.
[src/api/integrations/chatwoot/services/chatwoot.service.ts]
> const originalFilename = messageBody?.fileName || messageBody?.filename || messageBody?.message?.documentMessage?.fileName;
For files that do not have a filename, such as images, in chatwoot.service.ts, we use the mimetype property from the getBase64FromMediaMessage function and assign a name to it. However, the messageType property received from Meta was …
=> fix: Correction of media as attachments in chatwoot when using a Meta API Instance and not Baileys

src/api/services/monitor.service.ts
Without this change, if I have instance saved on redis and using database, it will clear from the database on logout but not from redis
=> Remove instance from redis even if using database

prisma/postgresql-migrations/20240813003116_make_label_unique_for_instance/migration.sql, prisma/postgresql-schema.prisma, src/api/services/channels/whatsapp.baileys.service.ts
This is to prevent this kind of error:
Since the label ID can be the same for different instances
=> Changed labels to be unique on the same instance

src/api/integrations/s3/libs/minio.server.ts, src/api/services/channels/whatsapp.baileys.service.ts, src/config/env.config.ts
1. O MinIO tem uma região padrão quando não informada a região ao criar o Client;
2. Ao fazer upload do arquivo foi notado que os metadados do arquivo setados (content-type e custom-header-application) não eram setados no arquivo no S3, inclusive o content-type era trocado pela detecção da AWS, ficando sempre como `binary/octet-stream`, então sempre quando acessa o link ele fazia download do arquivo, em vez de ter a preview.
1. Agora no S3 do .env tem pra colocar a região, caso não informada, pega o default normalmente do MinIO;
2. Isso estava acontecendo pois a função `uploadFile` recebia o size como parametro, mas em vez do número, chegava um objeto, se perdendo nos parametros da `putObject` que ignorava o metadata informado.
=> [v2] - Região no S3 e fix do size no uploadFile

prisma/mysql-schema.prisma, prisma/postgresql-migrations/20240817110155_add_trigger_type_advanced/migration.sql, prisma/postgresql-schema.prisma, src/api/integrations/dify/services/dify.service.ts, src/api/integrations/dify/validate/dify.schema.ts, src/api/integrations/openai/services/openai.service.ts, src/api/integrations/openai/validate/openai.schema.ts, src/api/integrations/typebot/services/typebot.service.ts, src/api/integrations/typebot/validate/typebot.schema.ts, src/utils/advancedOperatorsSearch.ts
> _Docs generate by AI_
---
This documentation describes the implementation of an advanced string search function using operators like `contains:`, `notContains:`, `startsWith:`, `endsWith:`, and `exact:`. The function allows for case-insensitive searches while ignoring accents. It supports both **AND** logic (when values are separated by a comma within the same operator) and **OR** logic (when multiple identical operators are used).
---
- **`contains:`**
- **Description**: Checks if the string contains the specified value.
- **AND**: If a comma is present, all comma-separated values must be present.
- **OR**: If multiple `contains:` operators are used, the string must satisfy at least one of the criteria.
- **Example**:
- `contains:Error,Access` (Searches for strings that contain …
=> Advanced operators trigger for OpenAI/Dify/Typebot

src/api/integrations/event/webhook/controllers/webhook.controller.ts
Este commit corrige a função de criar/atualizar um webhook pelo manager. Na implementação anterior, o código não estava entrando no bloco de catch e, consequentemente, não estava criando um novo webhook quando a instância não possuía um webhook criado.
=> Fix webhook creation

src/api/integrations/chatbot/dify/services/dify.service.ts
Este PR adiciona melhorias para resolver problemas de mensagens cortadas e falta de resposta inicial do chatbot que ocorre na integração com um agente no Dify. As alterações incluem:
- **Tratamento de múltiplos JSONs em um único chunk:** Agora, o código divide os chunks de dados em múltiplas linhas e filtra apenas os JSONs válidos, permitindo que várias mensagens sejam processadas corretamente.
- **Validação de strings JSON antes de processamento:** Uma verificação foi adicionada para garantir que apenas strings que começam com `{` sejam tratadas como JSON, evitando erros de parsing e garantindo que apenas dados válidos sejam processados.
Essas adições asseguram que a API da Evolution processe todas as mensagens de entrada de maneira robusta, eliminando os bugs previamente identificados, …
=> Fixed integration with Dify agents

src/api/services/cache.service.ts, src/cache/cacheengine.ts
"Minha proposta é alterar o nível dos logs do cache para 'verbose'. Acredito que isso ajudaria a manter os logs de info mais limpos, já que não é relevante gerar tantos logs sobre o uso do cache em cada operação."
=> [Proposta] Alterar level dos logs do cache para verbose

.env.example, src/api/services/channel.service.ts
It gives us a chance to define a proxy to be used by all instances on deploy
=> feat: Define a global proxy to be used if the instance does not have one

src/api/integrations/channel/whatsapp/whatsapp.baileys.service.ts
The return must be what the user informed and not the number result.
The number can be obtained from the JID, this is the same behavior that we had previously in v1
=> Fix on whatsapp number return

.gitignore, prisma/mysql-schema.prisma, prisma/postgresql-migrations/20240906202019_add_headers_on_webhook_config/migration.sql, prisma/postgresql-schema.prisma, src/api/controllers/instance.controller.ts, src/api/integrations/event/event.dto.ts, src/api/integrations/event/event.manager.ts, src/api/integrations/event/webhook/webhook.controller.ts, src/api/integrations/event/webhook/webhook.router.ts, src/api/integrations/event/webhook/webhook.schema.ts, src/api/types/wa.types.ts
Foi adicionada a opção de cadastrar headers junto ao webhook, de forma que possibilite adicionar uma camada de segurança e autenticação para a aplicação/serviço que receberá a chamada vinda da API da Evolution.
Segue o exemplo de como cadastrar abaixo:
```json
{
"webhook": {
"url": "...",
"headers": {
"autorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6Ik...",
"Content-Type": "application/json"
},
"byEvents": true,
"base64": false,
"events": [...]
}
}
=> feat: adiciona headers no cadastro de webhook da instância

.vscode/settings.json, CHANGELOG.md, docker-compose.dev.yaml, docker-compose.yaml, src/api/integrations/chatbot/chatbot.controller.ts
Using debounce message break as "\n" instead of white spaces allow Bot API to treat better these messages.
=> Debounce message break

src/api/integrations/channel/evolution/evolution.channel.service.ts, src/api/integrations/channel/whatsapp/whatsapp.baileys.service.ts
Ao criar o contato pelo evento de message.upsert estamos considerando que o pushName sempre será o nome do contato e isso não é verdade. Um outro ponto, tem problema em atualizar o nome do contato sempre que uma nova mensagem é recebida?
=> V2.0.0 contacts push name

prisma/mysql-migrations/20241001172800_add_message_status/migration.sql, prisma/mysql-schema.prisma, prisma/postgresql-migrations/20241001180457_add_message_status/migration.sql, prisma/postgresql-schema.prisma
Adicionado o campo status na entidade Message, esse campo estava faltando devido a commit: 
[feat: adiciona o status da mensagem no retorno da função "prepareMessage"
](https://github.com/EvolutionAPI/evolution-api/commit/68b5d8db4d3da1df139be160ecd3eb8abbac38f5)
Atualizado as migrations do MySQL que estavam desatualizadas.
=> fix: add migration field message status

src/api/controllers/sendMessage.controller.ts, src/api/integrations/channel/evolution/evolution.channel.service.ts, src/api/integrations/channel/meta/whatsapp.business.service.ts, src/api/integrations/channel/whatsapp/whatsapp.baileys.service.ts
An error in the WhatsApp audio message handler has been fixed. The system now checks if the file has a valid buffer before sending it. Additionally, validation has been added to verify if the audio is a valid URL or Base64. If these conditions are not met, an error message is shown, and a BadRequestException is thrown.
fix https://github.com/EvolutionAPI/evolution-api/issues/948
=> fix: Corrected audio file handling in WhatsApp

src/api/integrations/channel/whatsapp/whatsapp.baileys.service.ts
Currently, we face an issue when a file with the same name is uploaded more than once: 1.⁠ ⁠It results in a unique key error in the database. 2.⁠ ⁠If the file is sent to S3, it overwrites the old file.
To resolve this problem, I've implemented a solution where we concatenate the message ID to the filename. This approach ensures uniqueness for each uploaded file, even if users upload files with identical names multiple times in a chat.
This change allows normal users to upload files with the same name multiple times in a chat without encountering errors or unintended file overwrites.
=> Fix duplicate file upload

src/api/integrations/channel/whatsapp/whatsapp.baileys.service.ts, src/api/services/channel.service.ts
Correção para que o webhook passe a respeitar se deve ou não enviar o anexo de midia em base64 no webhook
#956
=> Escutar a configuração do webhook para midias recebidas

src/api/services/channel.service.ts
Adicionar ao retorno do endpoint findMessages(fetchMessages) o 'contextInfo' (essa info vem via websocket, mas não via API).
=> Add ContextInfo to return in FindMessages

src/api/integrations/chatbot/chatwoot/services/chatwoot.service.ts
This commit refactors the code in ChatwootService to update the content_attributes when replyToIds are present. Instead of directly spreading the replyToIds object, the code now converts it to a JSON string and appends it to the data object.
Refactor the code to improve readability and maintainability.
=> refactor: Update content_attributes in ChatwootService

src/api/integrations/channel/whatsapp/whatsapp.baileys.service.ts, src/api/integrations/chatbot/chatwoot/services/chatwoot.service.ts, src/utils/translations/en.json, src/utils/translations/es.json, src/utils/translations/pt-BR.json
Aprimoramento no método _onSendMessageError_:
**Tratamento de erro de contato sem WhatsApp:**
Anteriormente, quando um contato não possuía uma conta de WhatsApp, o sistema enviava duas mensagens de erro ao Chatwoot. Esse comportamento foi corrigido, e agora, apenas uma mensagem de erro é enviada, informando que o contato não possui WhatsApp.
Antes:
Depois:
**Exibição de erros retornando objetos:**
Em certos cenários, quando o método encontrava um erro e um objeto de erro era retornado, essa informação não era exibida no Chatwoot. A melhoria aplicada corrige essa situação, permitindo que erros que retornam objetos sejam devidamente apresentados na interface do Chatwoot, proporcionando maior clareza e rastreabilidade para os operadores.
Antes:
Depois:
**Outros**
Adicionado um log verbose do …
=> refactor: Remove unnecessary code for handling contact not in WhatsApp and onSendMessageError

src/api/controllers/instance.controller.ts, src/api/integrations/channel/whatsapp/whatsapp.baileys.service.ts, src/api/services/monitor.service.ts
This commit adds a new feature to fetch instances by key in the InstanceController. If the provided key does not match the environment key, the controller will search for instances with the matching token. If instances are found, the names are extracted and passed to the waMonitor to retrieve instance information.
Also, update the waMonitor's instanceInfo method to accept an array of instance names instead of a single name.
Fixes #990
=> feat: add support for fetching multiple instances by key

src/utils/getConversationMessage.ts
This update resolves an issue with the response button functionality on iOS devices. Previously, users reported unresponsive or delayed feedback when tapping the button. The fix ensures consistent behavior across iOS versions by optimizing touch event handling and enhancing button reactivity.
=> Fix Ios Response Button

src/api/integrations/chatbot/chatwoot/services/chatwoot.service.ts
Este PR realiza uma pequena melhoria no conteúdo das mensagens recebidas pelos grupos no WhatsApp, adicionando o número de telefone do remetente antes do nome do contato, facilitando a visualização do número diretamente na conversa.
Anteriormente, as mensagens enviadas para o Chatwoot continham apenas o nome do remetente no conteúdo da mensagem. Esta atualização adiciona o número de telefone do contato antes do nome, proporcionando melhor identificação do remetente sem a necessidade de procurar o número separadamente.
1. **Modificação no formato de exibição de mensagens recebidas**:
- O número de telefone do remetente agora é exibido antes do nome do contato na mensagem formatada.
```plaintext
**João Silva:** Olá! Gostaria de saber mais sobre os serviços.
```
```plaintext
**+55 (11) …
```
=> Adiciona o número de telefone do remetente nas mensagens recebidas do WhatsApp antes do nome do contato (GRUPOS)

prisma/mysql-migrations/20241108101333_fix_message_status_as_string/migration.sql
Identifiquei que o campo status na tabela Message era tratado como string, mas o ultimo migration o criava como int. Isso causou erros aqui em uma instalação nova na versão 2.2.0. As mensagens estavam sendo enviadas mas o servidor gerava um erro 500 ao tentar inserir na tabela.
=> Fix Message.Status as String

src/api/integrations/chatbot/chatwoot/services/chatwoot.service.ts
Este PR corrige o problema na exibição do número de telefone do remetente nas mensagens recebidas do WhatsApp, que anteriormente incluía um ID incorreto. Agora, o número é extraído corretamente a partir do campo `participant` para garantir que apenas o número de telefone do remetente seja exibido antes do nome do contato.
A extração anterior do número de telefone estava utilizando o campo `remoteJid`, que incluía um identificador incorreto. Este ajuste melhora a clareza da informação e garante que o número exibido seja o correto para facilitar o atendimento.
1. **Correção na extração do número de telefone do remetente**:
- Substitui a extração do número de `remoteJid` para o campo `participant`.
- O número agora é formatado corretamente e precede o nome do contato na mensagem. …
=> Correção: Número de telefone apresentado no nome do contato (CW Service)

src/api/integrations/chatbot/dify/services/dify.service.ts, src/api/integrations/chatbot/evolutionBot/services/evolutionBot.service.ts, src/api/integrations/chatbot/flowise/services/flowise.service.ts, src/api/integrations/chatbot/openai/services/openai.service.ts
Este PR resolve um problema onde o text buffer não é esvaziado corretamente quando splitMessages está configurado como true. Esse comportamento causa o envio incorreto das mensagens, pois a última mensagem enviada pelo chatbot no WhatsApp inclui também mensagens anteriores.
=> fix: esvazia textBuffer dos chatbots no sendMessageWhatsapp quando splitMessages é true

src/api/integrations/channel/meta/whatsapp.business.service.ts
Foi corrigido o envio de áudio para transcrição pela OpenAI, com as `env`s `LANGUAGE=pt` e `OPENAI_ENABLED=true` configuradas, via Cloud API.
=> Correção de envio de áudio para OpenAI via Cloud API

package.json, prisma/mysql-schema.prisma, prisma/postgresql-schema.prisma, src/api/integrations/channel/whatsapp/whatsapp.baileys.service.ts, src/api/services/channel.service.ts
Encontrei alguns problemas de concorrencia no Handle Label e principalmente duplicação de chats.
1. Ele primeiro fazia um get de todos os chats da instancia para depois realizar o update, caso o usuario adicionasse ou removesse labels ao mesmo tempo existia uma chance muito alta de sobrescrita de labels.
2. Como os chats não eram unicos isso quebrava a lógica das labels e várias outras.
3. Para o caso de duas instancias diferentes salvarem o mesmo numero o findChats retornava como se os numeros fossem da mesma instanceID.
4. No startup da aplicação as labels não eram carregadas adequadamente pois os chats não tinha sido salvos ainda.
1. Realizei as operações diretamente no banco de dados para um risco menor de racing.
2. Defini uma migration para que não hajam problemas com chats …
=> [FIX] Fixando label handler e chats

src/main.ts, src/utils/instrumentSentry.ts
O Sentry estava exibindo este alerta na instrumentação do pacote:
Com a atualização proposta segundo a documentação do Sentry não recebemos mais este aviso:
=> chore: improve instrumentSentry.ts import before another import

src/api/dto/instance.dto.ts
It fixes a minor issue while trying to create instances with webhook and chatwoot settings. Some body params werent being passed during instance creation.
=> fix: instance create w/webhook and chatwoot settings

src/api/integrations/channel/meta/whatsapp.business.service.ts
Adicionado suporte para o campo **filename** na payload de mensagens de mídia enviadas pela API do WhatsApp Business.
=> fix: include filename in media message payload for WhatsApp Business

src/api/services/channel.service.ts
Sending a POST request to `{{baseUrl}}/chat/findChats/{{instance}}` was returning an error `column \"updatedat\" does not exist"`.
=> bugfix: SQL query column quoting in ChannelStartupService

src/api/controllers/chat.controller.ts, src/api/dto/chat.dto.ts, src/api/integrations/channel/whatsapp/whatsapp.baileys.service.ts, src/api/routes/chat.router.ts, src/validate/chat.schema.ts
Percebi que a API Evolution ainda não oferecia suporte para obter o **catálogo de produtos** e as **coleções** de uma conta WhatsApp Business. Como isso pode ser útil para quem deseja integrar automações ou exibir os produtos via API, resolvi fazer esse fork e implementar essa funcionalidade.
Estou abrindo este **PR** com a intenção de contribuir e, caso faça sentido para o projeto, fico à disposição para ajustes ou melhorias! 😊
- 📌 **Uma nova rota para buscar o catálogo de produtos**
- 📌 **Uma nova rota para obter as coleções de produtos associadas à conta**
- 📌 **Resposta estruturada no seguinte formato:**
```shell
curl --location 'http://localhost:8080/chat/fetchCollections/instancia01' \
--header 'Content-Type: application/json' \
--header 'apikey: ••••••' \
--data '{
"number": …
```
=> Feat: Adicionei suporte para obter o Catálogos de Produtos e as Coleções de Produtos para a versão 2.2.3

src/api/integrations/channel/meta/whatsapp.business.service.ts
Greetings everyone, I encountered a problem while using Evolution API, when I received a location message from WhatsApp (Meta) the application did not resolve the message.
I noticed there was no integration with this type of messages yet so I hope this can help someone else.
=> feat: add message location support whatsapp meta

src/api/integrations/chatbot/chatwoot/services/chatwoot.service.ts
Hello, when using another language in Chatwoot the CSAT message changes and skips validation, when the survey link is sent chatwoot creates a new conversation.
=> fix: chatwoot csat creating new conversation in another language

prisma/mysql-migrations/1707735894523_add_wavoip_token_to_settings_table/migration.sql
A coluna `wavoipToken` estava ausente na tabela `Setting`, causando problemas na build do ambiente MySQL.
Adicionei uma migration que cria a coluna `wavoipToken` na tabela `Setting`.
Esta alteração garante que a coluna `wavoipToken` seja criada automaticamente, corrigindo o problema reportado na **Issue #1234**.
=> 🐛 Fix: Add migration for missing wavoipToken column in MySQL build env (#1234)

src/utils/getConversationMessage.ts
Essa falha para obter o .id causa a sessão em entrar no modo `awaitUser: false`, com isso, as interações acabam não chegando mais no typebot (e possivelmente em outros lugares que possuem essa mesma lógica)
Fiz o ajuste de optional chaining na hora de obter o mediaId, para evitar esse erro, e ajustei também o modo como o listResponseMessage é acesso (provavelmente alguma diferença relacionada a versão do baileys)
=> fix: change mediaId optional chaining and list response message text obtain

src/api/controllers/sendMessage.controller.ts
Agora é possível remover uma reação de uma mensagem enviando a chave `"reaction"` com uma **string vazia** no corpo da requisição.  
Para isso, foi necessário modificar a validação no método `sendReaction()`, que agora utiliza **regex** para garantir que:  
- Apenas um único emoji seja enviado.  
- Qualquer outro valor inválido (incluindo uma string vazia) retorne um `BadRequestException()`.  
O WhatsApp já possui a funcionalidade de remover uma reação, então essa implementação garante compatibilidade com o comportamento original da plataforma.  
Seria interessante adicionar essa informação à **documentação** para que os usuários saibam como remover reações corretamente.  
Além disso, uma **nova rota exclusiva para remoção** poderia tornar essa funcionalidade mais intuitiva. Caso seja …
=> ✨ Feat: Remover a reação de uma mensagem.

src/api/integrations/chatbot/typebot/controllers/typebot.controller.ts, src/api/integrations/chatbot/typebot/services/typebot.service.ts
Removi uma validação de await user na função do controller do typebot e coloquei ela posteriomente dentro do service (processTypebot)
Atualmente caso caia em uma situação onde a sessão está expirada, mas o awaitUser está false, não entra na função que efetua corretamente a reabertura da sessão expirada, ficando a sessão aberta até que seja manualmente deletada.
Tive esse problema acontendo ocasionalmente, e após procurar, encontrei uma issue citando esse mesmo problema #1260
=> Fix: Expiration being useless on awaitUser false

src/api/integrations/chatbot/chatwoot/services/chatwoot.service.ts
Este PR adiciona a possiblidade de envio de arquivos do tipo `SVG` e `TIFF` da mesma forma que faz com do tipo `GIF` vindas do Chatwoot.
Atualmente o WhatsApp WEB somente aceita imagens do tipo `JPG, PNG e WEBP` de forma nativa, `GIF` e `SVG` o core processa as imagens em `JPEG` e `PNG` respectivamente.
Como o Chatwoot não entende que isso é um problema no canal de API deles, visto que o envio do arquivo é feito puro. Então sim, se entende ser um problema da API. Devemos tratar esses attachs na API Evolution. 
Enviar os tipos `SVG` e `TIFF` da mesma forma que atualmente é feito com as imagens do tipo `GIF`.
Adicionei uma constante com um array de extensões de mimetype: image e que deverão ser enviadas como tipo document. O array permite a fácil inclusão de outros tipos de imagens que …
=> chore: possibilita o envio de medias do tipo [svg, tiff] vindas do Chatwoot

src/api/integrations/chatbot/typebot/services/typebot.service.ts
Esse PR corrige o erro Cannot read properties of undefined (reading 'applyFormatting') que ocorre quando o Typebot envia mensagens que o usuário precisa inserir uma resposta.
=> fix: correçao do typebot não conseguir ouvir mensagens de input
