EvolutionAPI/evolution-api

src/whatsapp/services/whatsapp.service.ts

Caso seja enviado everyOne como false sem passar nada no mentioned

[BUG] Correção de mencionar

---

src/whatsapp/abstract/abstract.router.ts

Reverts EvolutionAPI/evolution-api#34

Revert "GroupJid por Query ou por Body"

---

src/whatsapp/services/whatsapp.service.ts

Verifica todos os participantes e pega apenas os que existe no WhatsApp

[Melhoria] Group Create

---

src/whatsapp/services/monitor.service.ts

Referente relatado na issues, #94

Melhorando o desempenho no carregamento da instância. 

---

src/whatsapp/services/monitor.service.ts

Evolution ap i 1.5.1 - Problemas ao ler / consultar instancias (FETCH_INSTANCES)
Ao consultar instancias as mesmas nao apareciam, seja via manager, seja via postman

Update monitor.service.ts - Evolution ap i 1.5.1 - Problemas ao ler / consultar instancias (FETCH_INSTANCES)

---

CHANGELOG.md
src/whatsapp/models/chatwoot.model.ts

Fix misconfiguration on chatwoot model to store reopen_conversation and conversation_pending on database.

Fix chatwootSchema in chatwoot model to store reopen_conversation and conversation_pending options

---

src/whatsapp/services/whatsapp.service.ts

Correção nao recebimento de midias com urls do minio/s3 .
Urls sem o nome da extensão da midia impediam o envio das mensagens por erro na detecção do mimetype.

Correção de nao recebimento de midias armazenadas mo minio/s3 Update whatsapp.service.ts

---

src/whatsapp/services/typebot.service.ts

Foi criada a variável enabled_typebot (não obrigatória)
enabled_typebot igual a true ou vazio: o comportamento do "startTypebot" atua como a nova funcionalidadede sessões persistentes (v1.5.2) onde o flow do Typebot disparado atua como chatbot.
enabled_typebot igual a false: o comportamento do "startTypebot" atua como era na Evolution v.1.5.1 onde o flow do Typebot disparado atua como mensagem simples, nao ativa o chatbot e funciona apenas como mensagens simples.
Obs1: Se setada como true ou se for omitida essa variável no comando start Typebot, enabled_typebot será assumida como true, ou seja, start typebot aciona o flow com o chatbot ativado, imediatamente após o envio, aguardando interação do contato.. Se, antes do acionamento do start typebot, tiver um outro chatbot ativo, o mesmo …

Start Typebot com opção de ativar chatbot ou não

---

src/whatsapp/services/typebot.service.ts

Reverts EvolutionAPI/evolution-api#154

Revert "Start Typebot com opção de ativar chatbot ou não"

---

Dockerfile

Feita modificação no Dockerfile para utilização de compilação multi-estágio a fim de otimizar o tamanho final da imagem.
Com as modificações em questão, foi possível reduzir o tamanho da imagem em quase **40%** como pode ser observado abaixo:

Dockerfile modified to use multi-stage build

---

src/whatsapp/services/whatsapp.service.ts

Simply add info to log for admin purposes.

Add connected number and instance name to connected log

---

src/whatsapp/services/chatwoot.service.ts

fix: message can be undefined

---

src/whatsapp/services/whatsapp.service.ts

Ao disparar uma lista de mensagens, agora enviamos elas com o tipo 'PRODUCT_LIST' e realizamos a correção necessária na função patchMessageBeforeSending para o tipo 'SINGLE_SELECT'
`{{baseUrl}}/message/sendList/{{instance}}`
```
{
"number": "{{remoteJid}}",
"listMessage": {
"title": "List Title",
"description": "List description",
"buttonText": "Click Here",
"footerText": "footer list\nhttps://examplelink.com.br",
"sections": [
{
"title": "Row tilte 01",
"rows": [
{
"title": "Title row 01",
"description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,",
"rowId": "rowId 001"
},
{
"title": "Title row 02",
"description": "Lorem Ipsum is simply dummy text of the printing and typesetting …
```

fix: Correção na Função sendList

---

src/whatsapp/models/message.model.ts
src/whatsapp/services/chatwoot.service.ts
src/whatsapp/services/whatsapp.service.ts

It only works with messages read from whatsapp to chatwoot.

feat(chatwoot): read messages from whatsapp in chatwoot

---

src/whatsapp/services/chatwoot.service.ts

fix: message 'connection successfully' spamming

---

src/docs/swagger.yaml

Added sendList endpoint documentation

Added sendList endpoint to swagger documentation

---

.gitignore
package.json
src/config/env.config.ts
src/dev-env.yml
src/utils/i18n.ts
src/utils/translations/en.json
src/utils/translations/pt-BR.json
src/whatsapp/services/chatwoot.service.ts
src/whatsapp/services/typebot.service.ts

Add translated messages to CW when QRCode is generated

Add translate capabilities to QRMessages in CW

---

src/validate/validate.schema.ts
src/whatsapp/controllers/chat.controller.ts
src/whatsapp/dto/chat.dto.ts
src/whatsapp/routers/chat.router.ts
src/whatsapp/services/whatsapp.baileys.service.ts
src/whatsapp/services/whatsapp.business.service.ts

```
PUT
{{baseUrl}}/chat/updateBlockStatus/{{instance}}
{
"number": {{number}},
"status": "block" // unblock
}
```
#431

Add blockUser functionality

---

src/whatsapp/dto/typebot.dto.ts

Variável {{messageType}} adicionada para ser usada dentro do fluxo e a partir disso usar condições para fluxo seguir de acordo com o tipo de mensagem recebida:
Exemplo:
if {{messageTyp}} = audioMessage
if {{messageTyp}} = videoMessage
if {{messageTyp}} = imageMessage
if {{messageTyp}} = document
if {{messageTyp}} = conversation
Entre outras...
Exemplo:

Recurso para coletar tipo de mensagem

---

src/whatsapp/services/typebot.service.ts

Adicionado metodos para capturar diferentes tipos de mensagens alem do tipo texto.
Incluido:
AUDIO, VIDEO, IMAGEM, DOCUMENTOS E VISUALIZAÇÃO ÚNICA, Etc...

Reconhecer tipos de mensagens

---

src/api/controllers/chat.controller.ts
src/api/dto/chat.dto.ts
src/api/routes/chat.router.ts
src/api/services/channels/whatsapp.baileys.service.ts
src/api/services/channels/whatsapp.business.service.ts
src/validate/validate.schema.ts

I added a method to mark the chat as unread.

feat: method to mark chat as unread

---

Extras/chatwoot/criador_de_inbox.json

Update criador_de_inbox.json for Evolution v2.0

Update criador_de_inbox.json for Evolution v2.0

---

Docker/evolution_api_v2.yaml

Adição de algumas environments que imagino que estejam faltando.

Atualização Stack Evolution API v2

---

package.json
prisma/mysql-schema.prisma
prisma/postgresql-migrations/20240814202359_integrations_unification/migration.sql
prisma/postgresql-schema.prisma
src/api/integrations/dify/services/dify.service.ts
src/api/integrations/openai/services/openai.service.ts
src/api/integrations/typebot/services/typebot.service.ts
src/api/services/monitor.service.ts

**Unified Session Table**: Consolidated the separate session tables for OpenAI, Typebot, and Dify into a single, unified table to simplify data management and improve efficiency.
**Integration Validation**: Implemented a validation check to prevent multiple integrations from being triggered simultaneously. This ensures that an integration cannot be invoked if another one is currently active/paused.

V2 integration unification

---

src/api/dto/instance.dto.ts
src/api/integrations/channel/meta/whatsapp.business.service.ts

Fixes a problem when trying to upload media to S3 via Wpp Business API.
Also [fixes declaration of instanceDto.chatwootAutoCreate](https://github.com/EvolutionAPI/evolution-api/pull/849)

Fix wpp biz api upload media s3

---

src/api/integrations/chatbot/chatwoot/services/chatwoot.service.ts

This is the correct PR for this one: https://github.com/EvolutionAPI/evolution-api/pull/862

Fix chatwoot not mentioning the quoted message

---

src/utils/getConversationMessage.ts

Due to changes in the receipt of information

Update Facebook / Instagram ADS for whatsapp integration

---

CHANGELOG.md
src/api/integrations/chatbot/typebot/controllers/typebot.controller.ts

The current settings use the ignore jid only from default settings and doesn't check the bot settings

Fix ignoreJids on typebot

---

src/api/integrations/channel/whatsapp/whatsapp.baileys.service.ts

Esta PR refatora a função `sendMessage` no Baileys, trazendo as seguintes melhorias:
- Padroniza o retorno da função, utilizando a variável `messageRaw` em vez de `messageSent`.
Essa mudança visa garantir maior consistência no retorno das funções.

refactor: simplifica e padroniza envio de mensagens no Baileys

---

src/api/integrations/channel/whatsapp/whatsapp.baileys.service.ts

Foi realizada uma padronização na forma com que é tratada as mensagens vindas de historico, enviadas e recebidas dentro da integração do Baileys.

refactor: padroniza tratamento de mensagens no Baileys

---

src/api/integrations/chatbot/chatwoot/services/chatwoot.service.ts

Permite receber imagens e vídeos de visualização única direto no ChatWoot

Visualização Única no ChatWoot

---

Dockerfile
runWithProvider.js
src/cache/localcache.ts
src/config/env.config.ts

1. Adicionado o EXPOSE no Dockerfile
2. Retorno null, nas funçoes hGet e hSet do Localcache

update: docker with expose port and localcache hGet and hSet return null

---

prisma/postgresql-schema.prisma
src/api/integrations/channel/whatsapp/whatsapp.baileys.service.ts
src/api/services/channel.service.ts

- Fix update message status for read events
- Added unread messages integer for chat model

Added unreadMessages to chats

---

src/api/integrations/channel/whatsapp/whatsapp.baileys.service.ts
src/api/services/channel.service.ts

- Fix unreadMessages count.
- Added Added last message / null to fetch chats and sort by it.
- Improve message status update.
- Fix create / update multiples message.
Change "returns" in "message.upsert" and "message.update" to "continue" to allow the process of a list of messages.
Close [this issue](https://github.com/EvolutionAPI/evolution-api/issues/925)

Added last message to fetch chats

---

src/api/services/channel.service.ts

Fix duplicated entries for chat list over join message query

Fix fetch chats query

---

prisma/mysql-schema.prisma
prisma/postgresql-migrations/20241017144950_create_index/migration.sql
prisma/postgresql-schema.prisma

**Otimização de Banco de Dados:** Adicionada criação de índices em diversos modelos para melhorar o desempenho de consultas.
- **Chat:**
- Índice em `instanceId`
- Índice em `remoteJid`
- **Contact:**
- Índice em `instanceId`
- Índice em `remoteJid`
- **Message:**
- Índice em `instanceId`
- **MessageUpdate:**
- Índice em `instanceId`
- Índice em `messageId`
- **Setting:**
- Índice em `instanceId`
- **Webhook:**
- Índice em `instanceId`
Esses índices foram adicionados para melhorar a performance em consultas frequentes nesses campos, garantindo que o banco de dados possa processar consultas de forma mais eficiente.

Add indexes to improve performance in Evolution

---

src/api/controllers/instance.controller.ts

This commit should fix the filter by instanceName

FIX: Update instance.controller.ts to filter by instanceName

---

src/api/integrations/channel/meta/whatsapp.business.service.ts

Foi corrigido o carregamento de imagens via Cloud API através de diversas pequenas correções.

Correção de Imagens no Cloud API

---

src/api/integrations/chatbot/typebot/services/typebot.service.ts

Esse if visa corrigir esse problema de a conversa ir para pendente mesmo depois de aberta.

Quando a conversa está aberta e o cliente manda mensagem, o status da conversa muda para pendente.

---

package.json
runWithProvider.js

Este PR implementa as seguintes mudanças para garantir que os scripts do projeto funcionem corretamente no Windows:
1. **Adaptação de comandos Linux para Windows:**
- Substituição de comandos incompatíveis como `rm -rf` e `cp -r` por equivalentes nativos do Windows (`rmdir` e `xcopy`).
- Ajustes para garantir que caminhos sejam interpretados corretamente no ambiente Windows, utilizando barras invertidas (`\\`) e aspas duplas quando necessário.
2. **Dinamização do uso de `DATABASE_PROVIDER`:**
- Adicionada lógica no arquivo `runWithProvider.js` para substituir o placeholder `DATABASE_PROVIDER` dinamicamente, com base na variável de ambiente definida no `.env`.
- Em caso de ausência de `DATABASE_PROVIDER` no `.env`, o sistema utiliza o valor padrão (`postgresql`), com logs claros para o …

Adaptação de scripts e comandos para compatibilidade com Windows

---

src/api/integrations/event/webhook/webhook.controller.ts

Correction for webhook global, not working in latest version

[FIX]Correction of webhook global

---

src/api/dto/instance.dto.ts

Olá, fui gerar uma imagem com a versão de desenvolvimento (develop) e recebi o seguinte erro:

bugfix: import prisma types

---

src/api/integrations/channel/whatsapp/whatsapp.baileys.service.ts

Refactor logical message deletion in BaileysStartupService

Fix Message deletion in Whatsapp Bailey Service

---

src/api/integrations/chatbot/dify/services/dify.service.ts

On newer versions of Dify, messages are truncated when answering user. This fix prevents the truncated message and supports any Dify Version (agent)
Before:
After Fix:

fix(dify-service): Truncated messages (agent bot)

---

prisma/mysql-schema.prisma
prisma/postgresql-schema.prisma

Pessoal, a tabela estava com nome e case errado, o que impedia o evolution de criar instancias em uma instalacao nova na 2.2.3

Fix instance creation on v2.2.3

---

src/api/integrations/chatbot/chatwoot/services/chatwoot.service.ts

Isso corrige envio de audio a partir do chatwoot que estava ficando duplicado.

Fix audio send duplicate from chatwoot.

---

package-lock.json
src/api/integrations/event/sqs/sqs.controller.ts

- Implement dynamic queue creation based on enabled events 
- Add method to list existing queues for an instance 
- Improve error handling and logging for SQS operations 
- Remove unused queue removal methods 
- Update set method to handle queue creation/deletion on event changes 
- Add comments for future feature of forced queue deletion
Ps: later, you can transform some methods there into a service.

fix: Refactor SQS controller to correct bug in sqs events by instance
